### PR TITLE
Re-enable Reversing Labs.

### LINKED ISSUE #555: NPM packages with namespaces from ReversingLabs don't have namespace in name.
As at the time of reporting the number is 232 in NPM.

For example `@zettle-bo/react` is listed as `react`.

### PR DESCRIPTION
**Pull request by calebbrown**
- Will reprocesses all data.
- Based on analysis, there was one minor issue in the data. The bad data has been removed and a reprocess will add the missing report for alloy-icons (npm).

Fixes #555

### CODE REVIEW

**Comment by calebbrown** [comment]
@rhalar

**Review by rhalar — APPROVED** [review]
Thanks Caleb! We are ready to continue, there is a set of new advisories on the bucket.

Beware however, if you are reprocessing the whole bucket, we did fix the NPM namespace issues in our advisories as well, so I'm guessing they will gave a different hash, if that presents a problem?
We will also do any necessary withdrawals after this is re-enabled. I think perhaps one minor update will have to be done.

**Comment by PFCM** [comment]
Is there a way to see a dry run of what the ultimate changes to the repo would look like?

**Comment by calebbrown** [comment]
I have run a dry run locally, and everything looks okay. I see ~3820 updates, 760 new reports.

@rhalar I just wanted to confirm that adding the `"related": [ "RLMA-2024-xxxxx" ]` entries is intentional, and that exposing these in the official OSV part of the report is intentional - or if it might be better to remove these?

**Review by PFCM — APPROVED** [review]

**Comment by mgdcvetko** [comment]
Hi, I work with @rhalar on this project so I will try to answer your questions as he is offline for a few days. 

We do intentionally use the `related` field to connect update advisory to the original advisory for a malicious package, but we were under the impression that it won't be exposed and that it's on us to use it if we want and how we want. It does not provide any info in the official report so we would rather not have it in. Is there a way in which you can omit the `related` field?

**Comment by calebbrown** [comment]
Thanks for the update @mgdcvetko. Please take a look at #671. That PR will filter out the related field.

**Pull request merged**
